version: '3'
services:
  app:
    restart: always
    build: ./server
    working_dir: /server
    volumes:
      - ./server:/server
      - ~/.m2:/root/.m2
    ports:
      - "8090:8090"
    expose:
      - "8090"
    command: mvn flyway:migrate spring-boot:run
    links:
      - mysql:mysql
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: contact
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    restart: always
  client:
    container_name: client
    build: ./client
    working_dir: /client
    restart: always
    ports:
      - 80:80
      - 443:443